Repository UQdeco2800/2021-ext-studio-1, pull requests merged in 2021-10, with the labels that each got.

#106 Story screen
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/RainbowBridge.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/bridge/Bridge.java
  source/core/src/main/com/deco2800/game/components/bridge/Lane.java
  source/core/src/main/com/deco2800/game/components/bridge/Location.java
  source/core/src/main/com/deco2800/game/components/gameover/GameOverDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/components/tutorialmenu/TutorialDisplay.java
  source/core/src/main/com/deco2800/game/components/winscreen/GameWinDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/screens/GameStoryScreen.java
  source/core/src/test/com/deco2800/game/ai/tasks/AITaskComponentTest.java
  source/core/src/test/com/deco2800/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/deco2800/game/components/bridge/BridgeTest.java
  source/core/src/test/com/deco2800/game/events/EventHandlerTest.java
Labels: Done, team 4

#109 Revert "Story screen"
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/RainbowBridge.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/bridge/Bridge.java
  source/core/src/main/com/deco2800/game/components/bridge/Lane.java
  source/core/src/main/com/deco2800/game/components/bridge/Location.java
  source/core/src/main/com/deco2800/game/components/gameover/GameOverDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/components/tutorialmenu/TutorialDisplay.java
  source/core/src/main/com/deco2800/game/components/winscreen/GameWinDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/screens/GameStoryScreen.java
  source/core/src/test/com/deco2800/game/ai/tasks/AITaskComponentTest.java
  source/core/src/test/com/deco2800/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/deco2800/game/components/bridge/BridgeTest.java
  source/core/src/test/com/deco2800/game/events/EventHandlerTest.java
Labels: bug

#117 Team3 sprint3 final
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
Labels: bug, team 3, team 4

#181 Code smells
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/RainbowBridge.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/Component.java
  source/core/src/main/com/deco2800/game/components/bridge/Bridge.java
  source/core/src/main/com/deco2800/game/components/gameover/GameOverActions.java
  source/core/src/main/com/deco2800/game/components/gameover/GameOverDisplay.java
  source/core/src/main/com/deco2800/game/components/gamestory/GameStoryDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/deco2800/game/screens/GameWinScreen.java
  source/core/src/test/com/deco2800/game/components/bridge/BridgeTest.java
  source/core/src/test/com/deco2800/game/components/player/KeyboardPLayerInputComponentTest.java
  source/core/src/test/com/deco2800/game/components/player/PlayerActionsTest.java
Labels: bug, documentation, team 4

#183 User UI sprint4
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/deco2800/game/screens/GameWinScreen.java
  source/core/src/main/com/deco2800/game/screens/RagnorakRacer.java
Labels: Done, team 4
